'use client';
import React from 'react';
import ProviderRedux from '@/redux/Provider';
import RealLayout from './RealLayout';
import './globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ProviderRedux>
      <RealLayout>{children}</RealLayout>
    </ProviderRedux>
  );
}
